name: MSVC Build
on: workflow_dispatch

env:
  BUILD_CONFIGURATION: Game__Shipping__Win64

permissions:
  contents: write
  id-token: write
  issues: write

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Setup github SSH
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.UEPSEUDO_SSH_KEY }}
        known_hosts: unnecessary

    - name: Checkout SFV
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0 # needed to get commits since last tag
        ssh-key: ${{ secrets.UEPSEUDO_SSH_KEY }}

    - name: Add Rust to PATH
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 17 2022" ..
        msbuild /p:Configuration=${{env.BUILD_CONFIGURATION}} .\StriveFrameData\StriveFrameData.sln
        msbuild /p:Configuration=${{env.BUILD_CONFIGURATION}} .\RE-UE4SS\UE4SS\proxy_generator\proxy\proxy.sln

    - name: StandalonePackage
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        mkdir standalone\Mods\StriveFrameViewer\dlls
        mkdir standalone\UE4SS_Signatures
        cp .\build\StriveFrameData\${{env.BUILD_CONFIGURATION}}\StriveFrameData.dll .\standalone\Mods\StriveFrameViewer\dlls\main.dll
        cp .\build\Output\${{env.BUILD_CONFIGURATION}}\proxy\bin\dwmapi.dll .\standalone\dwmapi.dll
        cp .\build\Output\${{env.BUILD_CONFIGURATION}}\UE4SS\bin\UE4SS.dll .\standalone\UE4SS.dll
        cp .\prereqs\mods.txt .\standalone\Mods\mods.txt
        cp .\prereqs\UE4SS-settings.ini .\standalone\UE4SS-settings.ini
        cp .\prereqs\FText_Constructor.lua .\standalone\UE4SS_Signatures\FText_Constructor.lua

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: StriveFrameViewer_Standalone
        path: ${{github.workspace}}\standalone\
        if-no-files-found: error

    - name: UnverumPackage
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        mkdir unverum\ue4ss\StriveFrameViewer\dlls
        cp .\build\StriveFrameData\${{env.BUILD_CONFIGURATION}}\StriveFrameData.dll .\unverum\ue4ss\StriveFrameViewer\dlls\main.dll

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: StriveFrameViewer_Unverum
        path: ${{github.workspace}}\unverum\
        if-no-files-found: error



